# -*- coding: utf-8 -*-
"""final project web scraping q1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kl1nwY1ymIr3OeYykQEFLecytw9inhNr
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup

pd.set_option('display.max_columns',None)

url="https://en.wikipedia.org/wiki/List_of_highest-grossing_films"

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive'
}
page = requests.get(url, headers=headers)
soup= BeautifulSoup(page.content, 'html.parser')
tables=pd.read_html(page.text)
df = tables[0]
print(df.head())