# -*- coding: utf-8 -*-
"""final project web scraping q1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kl1nwY1ymIr3OeYykQEFLecytw9inhNr
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup

# apikey = api keys are free from https://www.omdbapi.com/

apiurl= "http://www.omdbapi.com/"


url="https://en.wikipedia.org/wiki/List_of_highest-grossing_films"

api_movie_data = []

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive'
}
page = requests.get(url, headers=headers)

soup= BeautifulSoup(page.content, 'html.parser')

tables=pd.read_html(page.text)

df = tables[0]

rank = df['Rank'].tolist()

titles =df['Title'].tolist()

years = df["Year"].tolist()

MovieData = {
    'MovieRank':rank,
    'MovieTitle':titles,
    'MovieYear':years
}

for title in titles: 
  params = {
      "t": title, 
      "apikey": apikey
  }

  response= requests.get(apiurl, params=params)
  data = response.json()

  if data["Response"] == "True":
    api_movie_data.append({
        "Title": data["Title"],
        "Genre": data["Genre"],
        "Director": data["Director"],
        "IMDB_Rating": data["imdbRating"],
        "Runtime": data["Runtime"],
        "Awards": data["Awards"],
    })
  else:
    print(f"Movie not found: {title}") 

MovieData_df= pd.DataFrame(MovieData)

MovieData_df.to_csv('MovieList.csv')

api_data = pd.DataFrame(api_movie_data)

api_data.to_csv("MovieDetails.csv")
