# -*- coding: utf-8 -*-
"""height_utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IaJqy_DZ32v2KJDLNK3S5tGzs0druoWP
"""

def parse_height_to_inches(height_text):

    if pd.isna(height_text):
        return None

    s = str(height_text).strip()

    match = re.search(r"(\d+)\s*[-'`]\s*(\d{1,2})", s)
    if match:
        feet = int(match.group(1))
        inches = int(match.group(2))
    else:

        match = re.search(r"(\d+)", s)
        if not match:
            return None
        feet = int(match.group(1))
        inches = 0

    total_inches = feet * 12 + inches
    return total_inches


def parse_height_to_cm(height_text):
    inches = parse_height_to_inches(height_text)
    if inches is None:
        return None
    return inches * 2.54