# -*- coding: utf-8 -*-
"""q2_mens_volleyball

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vAjPHwzlJaUY7wgKIpgv3hTa_uD1xwCE
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

def parse_height_to_inches(height_text):

    if pd.isna(height_text):
        return None

    s = str(height_text).strip()

    match = re.search(r"(\d+)\s*[-'`]\s*(\d{1,2})", s)
    if match:
        feet = int(match.group(1))
        inches = int(match.group(2))
    else:

        match = re.search(r"(\d+)", s)
        if not match:
            return None
        feet = int(match.group(1))
        inches = 0

    total_inches = feet * 12 + inches
    return total_inches


def parse_height_to_cm(height_text):
    inches = parse_height_to_inches(height_text)
    if inches is None:
        return None
    return inches * 2.54

mens_volleyball_urls = [
    ("City College of New York", "https://ccnyathletics.com/sports/mens-volleyball/roster"),
    ("Lehman College",          "https://lehmanathletics.com/sports/mens-volleyball/roster"),
    ("Brooklyn College",        "https://www.brooklyncollegeathletics.com/sports/mens-volleyball/roster"),
    ("John Jay College",        "https://johnjayathletics.com/sports/mens-volleyball/roster"),
    ("Baruch College",          "https://athletics.baruch.cuny.edu/sports/mens-volleyball/roster"),
    ("Medgar Evers College",    "https://mecathletics.com/sports/mens-volleyball/roster"),
    ("Hunter College",          "https://www.huntercollegeathletics.com/sports/mens-volleyball/roster"),
    ("York College",            "https://yorkathletics.com/sports/mens-volleyball/roster"),
    ("Ball State",              "https://ballstatesports.com/sports/mens-volleyball/roster"),
]

def scrape_one_mens_volleyball_roster(school_name, url):

    print(f"Scraping {school_name} ...")

    response = requests.get(url)
    response.raise_for_status()
    html = response.text

    tables = pd.read_html(html)

    roster_table = None

    for t in tables:
        cols_lower = [str(c).lower() for c in t.columns]
        if any(("ht" in c) or ("height" in c) for c in cols_lower):
            roster_table = t
            break

    if roster_table is None:
        print(f"  -> No table with height column found for {school_name}. Skipping.")
        return pd.DataFrame(columns=["school", "player_name", "height_raw"])

    name_col = None
    height_col = None

    for col in roster_table.columns:
        col_lower = str(col).lower()
        if name_col is None and ("name" in col_lower or "player" in col_lower):
            name_col = col
        if height_col is None and ("ht" in col_lower or "height" in col_lower):
            height_col = col

    if name_col is None or height_col is None:
        print(f"  -> Could not find name/height columns for {school_name}.")
        return pd.DataFrame(columns=["school", "player_name", "height_raw"])

    temp = roster_table[[name_col, height_col]].copy()
    temp.columns = ["player_name", "height_raw"]

    temp["school"] = school_name

    return temp[["school", "player_name", "height_raw"]]

all_rosters = []

for school, url in mens_volleyball_urls:
    df_school = scrape_one_mens_volleyball_roster(school, url)
    all_rosters.append(df_school)

mens_vb_df = pd.concat(all_rosters, ignore_index=True)

print("First few rows:")
print(mens_vb_df.head())
print("\nNumber of players scraped:", len(mens_vb_df))

mens_vb_df["height_in"] = mens_vb_df["height_raw"].apply(parse_height_to_inches)
mens_vb_df["height_cm"] = mens_vb_df["height_raw"].apply(parse_height_to_cm)

avg_height_in = mens_vb_df["height_in"].mean()
avg_height_cm = mens_vb_df["height_cm"].mean()

print("\nAverage men's volleyball height:")
print(f"{avg_height_in:.2f} inches  (~ {avg_height_cm:.2f} cm)")

mens_vb_df.to_csv("mens_volleyball.csv", index=False)
print("\nSaved file: mens_volleyball.csv")

df_valid = mens_vb_df.copy()

print("Original columns:", df_valid.columns.tolist())

name_col = None
for col in df_valid.columns:
    col_lower = str(col).lower()
    if "name" in col_lower or "player" in col_lower or "athlete" in col_lower:
        name_col = col
        break

if name_col is None:
    name_col = df_valid.columns[0]

df_valid = df_valid.rename(columns={name_col: "name"})

if "height_in" not in df_valid.columns:

    height_num_col = None
    for col in df_valid.columns:
        col_lower = str(col).lower()
        if ("height" in col_lower or "ht" in col_lower) and col != "height_raw":
            height_num_col = col
            break

    if height_num_col is not None:
        df_valid = df_valid.rename(columns={height_num_col: "height_in"})
        df_valid["height_in"] = pd.to_numeric(df_valid["height_in"], errors="coerce")
    else:

        if "height_raw" not in df_valid.columns:
            raise KeyError("No height_in or height_raw column found to compute numeric height.")
        df_valid["height_in"] = df_valid["height_raw"].apply(parse_height_to_inches)


if "height_raw" not in df_valid.columns:

    df_valid["height_raw"] = df_valid["height_in"].astype(str)

if "height_cm" not in df_valid.columns:
    df_valid["height_cm"] = df_valid["height_in"] * 2.54

if "school" not in df_valid.columns:
    df_valid["school"] = "Unknown school"

if "sport" not in df_valid.columns:
    df_valid["sport"] = "volleyball"

if "gender" not in df_valid.columns:
    df_valid["gender"] = "M"

if "team" not in df_valid.columns:
    df_valid["team"] = "Men's Volleyball"

df_valid = df_valid[df_valid["height_in"].notna()].copy()

df_valid = df_valid.sort_values("height_in", ascending=False)

df_valid["rank"] = df_valid["height_in"].rank(
    method="dense",
    ascending=False
).astype("Int64")

top5 = df_valid[df_valid["rank"] <= 5]

top5_display = top5[
    ["name",
     "height_raw",
     "school",
     "sport",
     "gender",
     "team",
     "height_in",
     "height_cm",
     "rank"]
]

top5_display