# -*- coding: utf-8 -*-
"""womens swimming

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zRa1MANYD8xs4xNPLMgAOQa71NYyUqlL
"""

#ReggyBellance
import requests
from bs4 import BeautifulSoup
import pandas as pd

Sports_teams = {
    'Womens_swiming': [
        'https://csidolphins.com/sports/womens-swimming-and-diving/roster/2023-2024?view=2',
        'https://queensknights.com/sports/womens-swimming-and-diving/roster/2019-20',
        'https://yorkathletics.com/sports/womens-swimming-and-diving/roster',
        'https://athletics.baruch.cuny.edu/sports/womens-swimming-and-diving/roster/2024-25?view=2',
        'https://www.brooklyncollegeathletics.com/sports/womens-swimming-and-diving/roster/2022-23?view=2',
        'https://lindenwoodlions.com/sports/womens-swimming-and-diving/roster/2021-22?view=2',
        'https://mckbearcats.com/sports/womens-swimming-and-diving/roster?view=2',
        'https://ramapoathletics.com/sports/womens-swimming-and-diving/roster?view=2',
        'https://keanathletics.com/sports/womens-swimming-and-diving/roster?view=2',
        'https://oneontaathletics.com/sports/womens-swimming-and-diving/roster/2021-22?view=2'
    ]
}

processed_heights = []

processed_names = []

for url in Sports_teams['Womens_swiming']:

  headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive'
}

  page = requests.get(url, headers = headers)

  soup = BeautifulSoup(page.content, 'html.parser')

  if page.status_code == 200:
    rawnames = soup.find_all('td', class_='sidearm-table-player-name')

    raw_height_tags = soup.find_all('td', class_='height')

    for raw_name in rawnames:
      x = raw_name.get_text().strip()
      processed_names.append(x)

    for height_tag in raw_height_tags:
      height_str = height_tag.get_text().strip()
      if '-' in height_str:
          parts = height_str.split('-')

          if len(parts) == 2 and parts[0].strip() and parts[1].strip():
              try:
                  feet = float(parts[0]) * 12
                  inches = float(parts[1])
                  height_in_inches = feet + inches
                  processed_heights.append(height_in_inches)
              except ValueError:

                  print(f"Warning: Could not convert height '{height_str}' to float for URL {url}. Skipping.")
          else:
              print(f"Warning: Malformed height string '{height_str}' (parts missing or empty) for URL {url}. Skipping.")
      else:
          print(f"Warning: Height string '{height_str}' does not contain '-' for URL {url}. Skipping.")




womens_swimming_data_processed = {
    'Name': processed_names,
    'Height(in inches)': processed_heights
}

womens_df = pd.DataFrame(womens_swimming_data_processed)
womens_df.to_csv('Womens Swimming Team Athletes.csv', index =False)

avg_womens_swim_height = round(float(womens_df['Height(in inches)'].mean()),2)
print(f'Average womens swimming team height: {avg_womens_swim_height}')

top_5_heights = womens_df.sort_values(by='Height(in inches)', ascending=False).head(5)
display(top_5_heights)